<?php

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->delete();

        $countries = array(
            array('code' => 'US', 'name' => 'United States','currency' => 'United States dollar	','iso_4217_currency_code' => 'USD'),
            array('code' => 'CA', 'name' => 'Canada','currency' => 'Canadian dollar','iso_4217_currency_code' => 'CAD'),
            array('code' => 'AF', 'name' => 'Afghanistan','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'AL', 'name' => 'Albania','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'DZ', 'name' => 'Algeria','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'AS', 'name' => 'American Samoa','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'AD', 'name' => 'Andorra','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'AO', 'name' => 'Angola','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'AI', 'name' => 'Anguilla','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'AQ', 'name' => 'Antarctica','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'AG', 'name' => 'Antigua and/or Barbuda','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'AR', 'name' => 'Argentina','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'AM', 'name' => 'Armenia','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'AW', 'name' => 'Aruba','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'AU', 'name' => 'Australia','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'AT', 'name' => 'Austria','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'AZ', 'name' => 'Azerbaijan','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'BS', 'name' => 'Bahamas','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'BH', 'name' => 'Bahrain','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'BD', 'name' => 'Bangladesh','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'BB', 'name' => 'Barbados','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'BY', 'name' => 'Belarus','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'BE', 'name' => 'Belgium','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'BZ', 'name' => 'Belize','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'BJ', 'name' => 'Benin','currency' => 'West African CFA franc','iso_4217_currency_code' => 'XOF'),
            array('code' => 'BM', 'name' => 'Bermuda','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'BT', 'name' => 'Bhutan','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'BO', 'name' => 'Bolivia','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'BA', 'name' => 'Bosnia and Herzegovina','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'BW', 'name' => 'Botswana','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'BV', 'name' => 'Bouvet Island','currency' => 'United States dollar	','iso_4217_currency_code' => 'USD'),
            array('code' => 'BR', 'name' => 'Brazil','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'IO', 'name' => 'British lndian Ocean Territory','currency' => 'United States dollar	','iso_4217_currency_code' => 'USD'),
            array('code' => 'BN', 'name' => 'Brunei Darussalam','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'BG', 'name' => 'Bulgaria','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'BF', 'name' => 'Burkina Faso','currency' => 'West African CFA franc','iso_4217_currency_code' => 'XOF'),
            array('code' => 'BI', 'name' => 'Burundi','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'KH', 'name' => 'Cambodia','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'CM', 'name' => 'Cameroon','currency' => 'Central African CFA franc','iso_4217_currency_code' => 'XAF'),
            array('code' => 'CV', 'name' => 'Cape Verde','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'KY', 'name' => 'Cayman Islands','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'CF', 'name' => 'Central African Republic','currency' => 'Central African CFA franc','iso_4217_currency_code' => 'XAF'),
            array('code' => 'TD', 'name' => 'Chad','currency' => 'Central African CFA franc','iso_4217_currency_code' => 'XAF'),
            array('code' => 'CL', 'name' => 'Chile','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'CN', 'name' => 'China','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'CX', 'name' => 'Christmas Island','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'CC', 'name' => 'Cocos (Keeling) Islands','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'CO', 'name' => 'Colombia','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'KM', 'name' => 'Comoros','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'CG', 'name' => 'Congo','currency' => 'Central African CFA franc','iso_4217_currency_code' => 'XAF'),
            array('code' => 'CK', 'name' => 'Cook Islands','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'CR', 'name' => 'Costa Rica','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'HR', 'name' => 'Croatia (Hrvatska)','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'CU', 'name' => 'Cuba','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'CY', 'name' => 'Cyprus','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'CZ', 'name' => 'Czech Republic','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'CD', 'name' => 'Democratic Republic of Congo','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'DK', 'name' => 'Denmark','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'DJ', 'name' => 'Djibouti','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'DM', 'name' => 'Dominica','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'DO', 'name' => 'Dominican Republic','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'TP', 'name' => 'East Timor','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'EC', 'name' => 'Ecudaor','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'EG', 'name' => 'Egypt','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'SV', 'name' => 'El Salvador','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'GQ', 'name' => 'Equatorial Guinea','currency' => 'Central African CFA franc','iso_4217_currency_code' => 'XAF'),
            array('code' => 'ER', 'name' => 'Eritrea','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'EE', 'name' => 'Estonia','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'ET', 'name' => 'Ethiopia','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'FK', 'name' => 'Falkland Islands (Malvinas)','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'FO', 'name' => 'Faroe Islands','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'FJ', 'name' => 'Fiji','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'FI', 'name' => 'Finland','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'FR', 'name' => 'France','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'FX', 'name' => 'France, Metropolitan','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'GF', 'name' => 'French Guiana','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'PF', 'name' => 'French Polynesia','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'TF', 'name' => 'French Southern Territories','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'GA', 'name' => 'Gabon','currency' => 'Central African CFA franc','iso_4217_currency_code' => 'XAF'),
            array('code' => 'GM', 'name' => 'Gambia','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'GE', 'name' => 'Georgia','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'DE', 'name' => 'Germany','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'GH', 'name' => 'Ghana','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'GI', 'name' => 'Gibraltar','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'GR', 'name' => 'Greece','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'GL', 'name' => 'Greenland','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'GD', 'name' => 'Grenada','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'GP', 'name' => 'Guadeloupe','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'GU', 'name' => 'Guam','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'GT', 'name' => 'Guatemala','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'GN', 'name' => 'Guinea','currency' => 'Central African CFA franc','iso_4217_currency_code' => 'XAF'),
            array('code' => 'GW', 'name' => 'Guinea-Bissau','currency' => 'West African CFA franc','iso_4217_currency_code' => 'XOF'),
            array('code' => 'GY', 'name' => 'Guyana','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'HT', 'name' => 'Haiti','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'HM', 'name' => 'Heard and Mc Donald Islands','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'HN', 'name' => 'Honduras','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'HK', 'name' => 'Hong Kong','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'HU', 'name' => 'Hungary','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'IS', 'name' => 'Iceland','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'IN', 'name' => 'India','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'ID', 'name' => 'Indonesia','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'IR', 'name' => 'Iran (Islamic Republic of)','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'IQ', 'name' => 'Iraq','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'IE', 'name' => 'Ireland','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'IL', 'name' => 'Israel','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'IT', 'name' => 'Italy','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'CI', 'name' => 'Ivory Coast','currency' => 'West African CFA franc','iso_4217_currency_code' => 'XOF'),
            array('code' => 'JM', 'name' => 'Jamaica','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'JP', 'name' => 'Japan','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'JO', 'name' => 'Jordan','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'KZ', 'name' => 'Kazakhstan','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'KE', 'name' => 'Kenya','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'KI', 'name' => 'Kiribati','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'KP', 'name' => 'Korea, Democratic People\'s Republic of','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'KR', 'name' => 'Korea, Republic of','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'KW', 'name' => 'Kuwait','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'KG', 'name' => 'Kyrgyzstan','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'LA', 'name' => 'Lao People\'s Democratic Republic','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'LV', 'name' => 'Latvia','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'LB', 'name' => 'Lebanon','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'LS', 'name' => 'Lesotho','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'LR', 'name' => 'Liberia','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'LY', 'name' => 'Libyan Arab Jamahiriya','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'LI', 'name' => 'Liechtenstein','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'LT', 'name' => 'Lithuania','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'LU', 'name' => 'Luxembourg','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'MO', 'name' => 'Macau','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'MK', 'name' => 'Macedonia','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'MG', 'name' => 'Madagascar','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'MW', 'name' => 'Malawi','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'MY', 'name' => 'Malaysia','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'MV', 'name' => 'Maldives','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'ML', 'name' => 'Mali','currency' => 'West African CFA franc','iso_4217_currency_code' => 'XOF'),
            array('code' => 'MT', 'name' => 'Malta','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'MH', 'name' => 'Marshall Islands','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'MQ', 'name' => 'Martinique','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'MR', 'name' => 'Mauritania','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'MU', 'name' => 'Mauritius','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'TY', 'name' => 'Mayotte','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'MX', 'name' => 'Mexico','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'FM', 'name' => 'Micronesia, Federated States of','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'MD', 'name' => 'Moldova, Republic of','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'MC', 'name' => 'Monaco','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'MN', 'name' => 'Mongolia','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'MS', 'name' => 'Montserrat','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'MA', 'name' => 'Morocco','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'MZ', 'name' => 'Mozambique','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'MM', 'name' => 'Myanmar','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'NA', 'name' => 'Namibia','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'NR', 'name' => 'Nauru','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'NP', 'name' => 'Nepal','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'NL', 'name' => 'Netherlands','currency' => 'United States dollar	','iso_4217_currency_code' => 'USD'),
            array('code' => 'AN', 'name' => 'Netherlands Antilles','currency' => 'United States dollar	','iso_4217_currency_code' => 'USD'),
            array('code' => 'NC', 'name' => 'New Caledonia','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'NZ', 'name' => 'New Zealand','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'NI', 'name' => 'Nicaragua','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'NE', 'name' => 'Niger','currency' => 'West African CFA franc','iso_4217_currency_code' => 'XOF'),
            array('code' => 'NG', 'name' => 'Nigeria','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'NU', 'name' => 'Niue','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'NF', 'name' => 'Norfork Island','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'MP', 'name' => 'Northern Mariana Islands','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'NO', 'name' => 'Norway','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'OM', 'name' => 'Oman','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'PK', 'name' => 'Pakistan','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'PW', 'name' => 'Palau','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'PA', 'name' => 'Panama','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'PG', 'name' => 'Papua New Guinea','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'PY', 'name' => 'Paraguay','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'PE', 'name' => 'Peru','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'PH', 'name' => 'Philippines','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'PN', 'name' => 'Pitcairn','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'PL', 'name' => 'Poland','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'PT', 'name' => 'Portugal','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'PR', 'name' => 'Puerto Rico','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'QA', 'name' => 'Qatar','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'SS', 'name' => 'Republic of South Sudan','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'RE', 'name' => 'Reunion','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'RO', 'name' => 'Romania','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'RU', 'name' => 'Russian Federation','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'RW', 'name' => 'Rwanda','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'KN', 'name' => 'Saint Kitts and Nevis','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'LC', 'name' => 'Saint Lucia','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'VC', 'name' => 'Saint Vincent and the Grenadines','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'WS', 'name' => 'Samoa','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'SM', 'name' => 'San Marino','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'ST', 'name' => 'Sao Tome and Principe','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'SA', 'name' => 'Saudi Arabia','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'SN', 'name' => 'Senegal','currency' => 'West African CFA franc','iso_4217_currency_code' => 'XOF'),
            array('code' => 'RS', 'name' => 'Serbia','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'SC', 'name' => 'Seychelles','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'SL', 'name' => 'Sierra Leone','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'SG', 'name' => 'Singapore','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'SK', 'name' => 'Slovakia','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'SI', 'name' => 'Slovenia','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'SB', 'name' => 'Solomon Islands','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'SO', 'name' => 'Somalia','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'ZA', 'name' => 'South Africa','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'GS', 'name' => 'South Georgia South Sandwich Islands','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'ES', 'name' => 'Spain','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'LK', 'name' => 'Sri Lanka','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'SH', 'name' => 'St. Helena','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'PM', 'name' => 'St. Pierre and Miquelon','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'SD', 'name' => 'Sudan','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'SR', 'name' => 'Suriname','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'SJ', 'name' => 'Svalbarn and Jan Mayen Islands','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'SZ', 'name' => 'Swaziland','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'SE', 'name' => 'Sweden','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'CH', 'name' => 'Switzerland','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'SY', 'name' => 'Syrian Arab Republic','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'TW', 'name' => 'Taiwan','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'TJ', 'name' => 'Tajikistan','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'TZ', 'name' => 'Tanzania, United Republic of','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'TH', 'name' => 'Thailand','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'TG', 'name' => 'Togo','currency' => 'West African CFA franc','iso_4217_currency_code' => 'XOF'),
            array('code' => 'TK', 'name' => 'Tokelau','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'TO', 'name' => 'Tonga','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'TT', 'name' => 'Trinidad and Tobago','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'TN', 'name' => 'Tunisia','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'TR', 'name' => 'Turkey','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'TM', 'name' => 'Turkmenistan','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'TC', 'name' => 'Turks and Caicos Islands','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'TV', 'name' => 'Tuvalu','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'UG', 'name' => 'Uganda','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'UA', 'name' => 'Ukraine','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'AE', 'name' => 'United Arab Emirates','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'GB', 'name' => 'United Kingdom','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'UM', 'name' => 'United States minor outlying islands','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'UY', 'name' => 'Uruguay','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'UZ', 'name' => 'Uzbekistan','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'VU', 'name' => 'Vanuatu','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'VA', 'name' => 'Vatican City State','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'VE', 'name' => 'Venezuela','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'VN', 'name' => 'Vietnam','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'VG', 'name' => 'Virgin Islands (British)','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'VI', 'name' => 'Virgin Islands (U.S.)','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'WF', 'name' => 'Wallis and Futuna Islands','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'EH', 'name' => 'Western Sahara','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'YE', 'name' => 'Yemen','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'YU', 'name' => 'Yugoslavia','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'ZR', 'name' => 'Zaire','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'ZM', 'name' => 'Zambia','currency' => '...','iso_4217_currency_code' => '...'),
            array('code' => 'ZW', 'name' => 'Zimbabwe','currency' => '...','iso_4217_currency_code' => '...'),
        );

        DB::table('countries')->insert($countries);
    }
}
